name: Run Locust Tests

on: [push]

jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Locust Performance Tests
        uses: thomasvjoseph/locust@v1.1.5
        with:
          URL: https://www.netflix.com
          LOCUSTFILE: locustfile.py
          USERS: 2   # Reduced number of users
          RATE: 1    # Reduced request rate
          RUNTIME: 10s
          HEADLESS: true
          LOGLEVEL: DEBUG
          html_report: 'example.html'
      
      - name: List Files in Workspace
        run: ls -l

      - name: Upload Locust Test Results
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: example.html
          if-no-files-found: warn
          retention-days: 1
