name: Run Locust Tests

on: [push]

jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Locust Performance Tests
        uses: thomasvjoseph/locust@v1.1.4
        with:
          URL: https://www.netflix.com
          LOCUSTFILE: locustfile.py
          USERS: 2   # Reduced number of users
          RATE: 1    # Reduced request rate
          RUNTIME: 30s
          HEADLESS: true
          LOGLEVEL: DEBUG
          
      - name: Upload Locust Test Results
        uses: actions/upload-artifact@v2
        with:
          name: locust-report
          path: load_test_report.html